name: CI/CD - Child 01 App

on:
  workflow_dispatch:

  workflow_call:

permissions:
  contents: read

jobs:
  application:
    name: "Application"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print
        run: |
          echo Validating app for child 01.
          echo Building app for child 01.
          echo Deploying app for child 01.
