name: CI/CD - Child 01 Infra

on:
  workflow_dispatch:

  workflow_call:

permissions:
  contents: read

jobs:
  infrastructure:
    name: "Infrastructure"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print
        run: |
          echo Validating infra for child 01.
          echo Building infra for child 01.
          echo Deploying infra for child 01.
