name: CI/CD - Child 02

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print
        run: |
          echo Execute child 02 ci/cd pipeline.
          echo Testing child 02 ci/cd pipeline.
